image: ubuntu/latest
packages:
  - curl
  - libegl1-mesa-dev
  - libgles2-mesa-dev
  - pkg-config
  - libssl-dev
sources:
  - https://github.com/iceiix/stevenarella
tasks:
  - setup: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
      sh ./rustup.sh -y
      source $HOME/.cargo/env
      cargo +nightly --version
  - build: |
      source $HOME/.cargo/env
      cd stevenarella
      cargo +nightly build
      cargo +nightly test
