version: 2.1
executors:
    docker:
        docker:
            - image: circleci/rust:1.35.0
jobs:
    build:
        executor: docker
        steps:
            - run:
                name: The First Step
                command: |
                    echo 'Hello world!'
                    echo 'This is the delivery pipeline'

