version: 2.1
executors:
    docker:
        parameters:
            version:
                type: string
                default: 1.35.0
        docker:
            - image: circleci/rust:<< parameters.version >>
jobs:
    build:
        executor: docker
        parameters:
            release:
                type: boolean
                default: false
        steps:
            - install_deps
            - checkout
            - restore_cache:
                keys:
                    - cargo-cache-v1-{{ arch }}-{{ checksum "./Cargo.lock" }}
                    - cargo-cache-v1-{{ arch }}
            - run:
                name: Build
                command: |
                    rustc --version --verbose
                    cargo --version --verbose
                    if [ "<< parameters.release >>" == "true" ]; then
                        cargo build --release
                        cargo test --release
                    else
                        cargo build
                        cargo test
                    fi
            - save_cache:
                key: cargo-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "./Cargo.lock" }}
                paths:
                    - ./target
commands:
    install_deps:
        steps:
            - run:
                name: Install deps
                command: |
                    apt-get update -qq
                    apt-get install -y gcc libegl1-mesa-dev libgles2-mesa-dev

