[package]
name = "steven_gl"
version = "0.0.1"
authors = [ "Thinkofdeath <thinkofdeath@spigotmc.org>" ]
edition = "2018"
build = "build.rs"

[build-dependencies]
gl_generator = "0.14.0"
khronos_api = "3.1.0"

[dependencies]
libc = "0.2.71"
